version: '3.7'

services:
    web:
        build: ./web
        ports:
            - '5000:5000'
        links:
            - db
    db:
        build: ./db
    tfserver:
        image: mansong/resnet_serving
        ports:
            - '8500:8500'
            - '8501:8501'